### PR TITLE
Adding default episode image if one is not present in feed

### PR DESCRIPTION
**Pull request by rickyphewitt**
I've added a default for feeds that don't have a media:thumbnail.

### CODE REVIEW

**Comment by Xmetalfanx** [comment]
Oops .... got (the merge) that time lol .... like i said I am somewhat new to github and git in general

**Comment by rickyphewitt** [comment]
No problem. I hope you didn't mind me adding to your code. I'm pretty new to the kodi plugin scene and just wanted to help JB :)

**Comment by Xmetalfanx** [comment]
this is taking longer than expected here, but thanks to some good links from Rikai, I am trying my luck at squashing commits ... I am not sure if I am doing this right, or making more of a mess of things, so I am testing things on  something else I am working on for the time being.

I see the addition of the commit where I combined a few, but the question I have is "are the old commits (aka what combined) suppose to 'disappear' from the commit 'list' ? " .... I thought they were suppose to but then again this little bit is going over my head for some reason.

Main thing is I want to help JB and don't want to disappoint them if I am lucky enough to get this "merged" (my terminology there) with the main JB addon

**Comment by rickyphewitt** [comment]
Yea, I'm not that good with squashing commits... I try to avoid them ha. I"m sure my pull request on your pull request didn't make things easier :(

If you still having issues let me know and I can try to pull your frodo branch down and look at squash merging.

**Pull request merged**
